/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.11
 * Generated at: 2025-09-07 22:54:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class confirmacao_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    <!DOCTYPE html>\r\n");
      out.write("	<html lang=\"pt-BR\">\r\n");
      out.write("	<head>\r\n");
      out.write("	    <meta charset=\"UTF-8\">\r\n");
      out.write("	    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("	    <title>Confirmação de Reserva - Hotel Reservas</title>\r\n");
      out.write("	    <script src=\"https://cdn.tailwindcss.com\"></script>\r\n");
      out.write("	    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("	</head>\r\n");
      out.write("	<body class=\"bg-gradient-to-br from-blue-50 to-indigo-100 min-h-screen\">\r\n");
      out.write("	    <!-- Página 2: Confirmação e Dados -->\r\n");
      out.write("	    <div id=\"page2\" class=\"page active\">\r\n");
      out.write("	        <div class=\"container mx-auto px-4 py-8\">\r\n");
      out.write("	            <header class=\"text-center mb-8\">\r\n");
      out.write("	                <h1 class=\"text-4xl font-bold text-gray-800 mb-2\">🏨 Finalizar Reserva</h1>\r\n");
      out.write("	                <p class=\"text-gray-600\">Complete seus dados para confirmar</p>\r\n");
      out.write("	            </header>\r\n");
      out.write("	\r\n");
      out.write("	            <div class=\"max-w-4xl mx-auto\">\r\n");
      out.write("	                <div class=\"grid grid-cols-1 lg:grid-cols-2 gap-8\">\r\n");
      out.write("	                    <!-- Resumo da Reserva -->\r\n");
      out.write("	                    <div class=\"bg-white rounded-lg shadow-lg p-6\">\r\n");
      out.write("	                        <h2 class=\"text-2xl font-semibold text-gray-800 mb-4\">📋 Resumo da Reserva</h2>\r\n");
      out.write("	                        <div id=\"reservationSummary\" class=\"space-y-4\">\r\n");
      out.write("	                            <!-- Conteúdo será preenchido via JavaScript -->\r\n");
      out.write("	                        </div>\r\n");
      out.write("	                        <div class=\"border-t pt-4 mt-4\">\r\n");
      out.write("	                            <div class=\"flex justify-between items-center text-xl font-bold text-gray-800\">\r\n");
      out.write("	                                <span>Total:</span>\r\n");
      out.write("	                                <span id=\"totalPrice\">R$ 0</span>\r\n");
      out.write("	                            </div>\r\n");
      out.write("	                        </div>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	\r\n");
      out.write("	                    <!-- Formulário de Dados -->\r\n");
      out.write("	                    <div class=\"bg-white rounded-lg shadow-lg p-6\">\r\n");
      out.write("	                        <h2 class=\"text-2xl font-semibold text-gray-800 mb-4\">👤 Dados do Hóspede</h2>\r\n");
      out.write("	                        <form id=\"reservationForm\" class=\"space-y-4\">\r\n");
      out.write("	                            <div>\r\n");
      out.write("	                                <label class=\"block text-sm font-medium text-gray-700 mb-2\">Nome Completo</label>\r\n");
      out.write("	                                <input type=\"text\" id=\"fullName\" required\r\n");
      out.write("	                                    class=\"w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500\">\r\n");
      out.write("	                            </div>\r\n");
      out.write("	                            <div>\r\n");
      out.write("	                                <label class=\"block text-sm font-medium text-gray-700 mb-2\">Email</label>\r\n");
      out.write("	                                <input type=\"email\" id=\"email\" required\r\n");
      out.write("	                                    class=\"w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500\">\r\n");
      out.write("	                            </div>\r\n");
      out.write("	                            <div>\r\n");
      out.write("	                                <label class=\"block text-sm font-medium text-gray-700 mb-2\">Telefone</label>\r\n");
      out.write("	                                <input type=\"tel\" id=\"phone\" required\r\n");
      out.write("	                                    class=\"w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500\">\r\n");
      out.write("	                            </div>\r\n");
      out.write("	                            <div>\r\n");
      out.write("	                                <label class=\"block text-sm font-medium text-gray-700 mb-2\">CPF</label>\r\n");
      out.write("	                                <input type=\"text\" id=\"cpf\" required\r\n");
      out.write("	                                    class=\"w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500\">\r\n");
      out.write("	                            </div>\r\n");
      out.write("	\r\n");
      out.write("	                            <div class=\"space-y-3\">\r\n");
      out.write("	                                <h3 class=\"text-lg font-medium text-gray-800\">Serviços Adicionais</h3>\r\n");
      out.write("	                                <div class=\"flex items-center\">\r\n");
      out.write("	                                    <input type=\"checkbox\" id=\"breakfast\" class=\"mr-2\">\r\n");
      out.write("	                                    <label for=\"breakfast\" class=\"text-sm text-gray-700\">Café da manhã (+R$\r\n");
      out.write("	                                        25/dia)</label>\r\n");
      out.write("	                                </div>\r\n");
      out.write("	                                <div class=\"flex items-center\">\r\n");
      out.write("	                                    <input type=\"checkbox\" id=\"parking\" class=\"mr-2\">\r\n");
      out.write("	                                    <label for=\"parking\" class=\"text-sm text-gray-700\">Estacionamento (+R$\r\n");
      out.write("	                                        15/dia)</label>\r\n");
      out.write("	                                </div>\r\n");
      out.write("	                                <div class=\"flex items-center\">\r\n");
      out.write("	                                    <input type=\"checkbox\" id=\"spa\" class=\"mr-2\">\r\n");
      out.write("	                                    <label for=\"spa\" class=\"text-sm text-gray-700\">Acesso ao SPA (+R$ 50/dia)</label>\r\n");
      out.write("	                                </div>\r\n");
      out.write("	                            </div>\r\n");
      out.write("	\r\n");
      out.write("	                            <div class=\"flex space-x-4 pt-4\">\r\n");
      out.write("	                                <button type=\"button\" id=\"backBtn\"\r\n");
      out.write("	                                    class=\"flex-1 bg-gray-500 hover:bg-gray-600 text-white font-semibold py-3 px-6 rounded-lg transition duration-300\">\r\n");
      out.write("	                                    ← Voltar\r\n");
      out.write("	                                </button>\r\n");
      out.write("	                                <button type=\"submit\"\r\n");
      out.write("	                                    class=\"flex-1 bg-green-600 hover:bg-green-700 text-white font-semibold py-3 px-6 rounded-lg transition duration-300\">\r\n");
      out.write("	                                    Confirmar Reserva ✓\r\n");
      out.write("	                                </button>\r\n");
      out.write("	                            </div>\r\n");
      out.write("	                        </form>\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                </div>\r\n");
      out.write("	            </div>\r\n");
      out.write("	        </div>\r\n");
      out.write("	    </div>\r\n");
      out.write("	\r\n");
      out.write("	    <!-- Modal de Confirmação -->\r\n");
      out.write("	    <div id=\"confirmationModal\"\r\n");
      out.write("	        class=\"fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 hidden\">\r\n");
      out.write("	        <div class=\"bg-white rounded-lg p-8 max-w-md mx-4\">\r\n");
      out.write("	            <div class=\"text-center\">\r\n");
      out.write("	                <div class=\"text-6xl mb-4\">✅</div>\r\n");
      out.write("	                <h2 class=\"text-2xl font-bold text-gray-800 mb-4\">Reserva Confirmada!</h2>\r\n");
      out.write("	                <p class=\"text-gray-600 mb-6\">Sua reserva foi processada com sucesso. Você receberá um email de\r\n");
      out.write("	                    confirmação em breve.</p>\r\n");
      out.write("	                <div class=\"bg-gray-100 rounded-lg p-4 mb-6\">\r\n");
      out.write("	                    <p class=\"text-sm text-gray-700\"><strong>Código da Reserva:</strong></p>\r\n");
      out.write("	                    <p class=\"text-lg font-mono font-bold text-blue-600\" id=\"reservationCode\"></p>\r\n");
      out.write("	                </div>\r\n");
      out.write("	                <button id=\"closeModal\"\r\n");
      out.write("	                    class=\"bg-blue-600 hover:bg-blue-700 text-white font-semibold py-2 px-6 rounded-lg transition duration-300\">\r\n");
      out.write("	                    Fechar\r\n");
      out.write("	                </button>\r\n");
      out.write("	            </div>\r\n");
      out.write("	        </div>\r\n");
      out.write("	    </div>\r\n");
      out.write("	\r\n");
      out.write("	    <script src=\"js/script.js\"></script>\r\n");
      out.write("	</body>\r\n");
      out.write("	</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
