/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.11
 * Generated at: 2025-09-07 20:20:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"pt-BR\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Hotel Reservas - Sistema de Agendamento</title>\r\n");
      out.write("    <script src=\"https://cdn.tailwindcss.com\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-gradient-to-br from-blue-50 to-indigo-100 min-h-screen\">\r\n");
      out.write("    <!-- Página 1: Seleção de Quartos -->\r\n");
      out.write("    <div id=\"page1\" class=\"page active\">\r\n");
      out.write("        <div class=\"container mx-auto px-4 py-8\">\r\n");
      out.write("            <header class=\"text-center mb-8\">\r\n");
      out.write("                <h1 class=\"text-4xl font-bold text-gray-800 mb-2\">🏨 Hotel Reservas</h1>\r\n");
      out.write("                <p class=\"text-gray-600\">Selecione seu quarto ideal</p>\r\n");
      out.write("            </header>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"max-w-6xl mx-auto\">\r\n");
      out.write("                <div class=\"bg-white rounded-lg shadow-lg p-6 mb-8\">\r\n");
      out.write("                    <h2 class=\"text-2xl font-semibold text-gray-800 mb-4\">Filtros de Busca</h2>\r\n");
      out.write("                    <div class=\"grid grid-cols-1 md:grid-cols-3 gap-4\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <label class=\"block text-sm font-medium text-gray-700 mb-2\">Check-in</label>\r\n");
      out.write("                            <input type=\"date\" id=\"checkin\"\r\n");
      out.write("                                class=\"w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <label class=\"block text-sm font-medium text-gray-700 mb-2\">Check-out</label>\r\n");
      out.write("                            <input type=\"date\" id=\"checkout\"\r\n");
      out.write("                                class=\"w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <label class=\"block text-sm font-medium text-gray-700 mb-2\">Hóspedes</label>\r\n");
      out.write("                            <select id=\"guests\"\r\n");
      out.write("                                class=\"w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500\">\r\n");
      out.write("                                <option value=\"1\">1 Hóspede</option>\r\n");
      out.write("                                <option value=\"2\">2 Hóspedes</option>\r\n");
      out.write("                                <option value=\"3\">3 Hóspedes</option>\r\n");
      out.write("                                <option value=\"4\">4 Hóspedes</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6\">\r\n");
      out.write("                    <!-- Quarto Standard -->\r\n");
      out.write("                    <div class=\"room-card bg-white rounded-lg shadow-lg overflow-hidden\">\r\n");
      out.write("                        <div class=\"h-48 bg-gradient-to-r from-blue-400 to-blue-600 flex items-center justify-center\">\r\n");
      out.write("                            <span class=\"text-6xl\">🛏️</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"p-6\">\r\n");
      out.write("                            <h3 class=\"text-xl font-semibold text-gray-800 mb-2\">Quarto Standard</h3>\r\n");
      out.write("                            <p class=\"text-gray-600 mb-4\">Quarto confortável com cama de casal, ar-condicionado e Wi-Fi\r\n");
      out.write("                                gratuito.</p>\r\n");
      out.write("                            <div class=\"flex items-center justify-between mb-4\">\r\n");
      out.write("                                <span class=\"text-2xl font-bold text-blue-600\">R$ 150/noite</span>\r\n");
      out.write("                                <span class=\"text-sm text-gray-500\">👥 2 pessoas</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"flex items-center mb-4\">\r\n");
      out.write("                                <input type=\"checkbox\" id=\"room1\" class=\"room-checkbox mr-2\" data-room=\"Standard\"\r\n");
      out.write("                                    data-price=\"150\">\r\n");
      out.write("                                <label for=\"room1\" class=\"text-sm text-gray-700\">Selecionar este quarto</label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Quarto Deluxe -->\r\n");
      out.write("                    <div class=\"room-card bg-white rounded-lg shadow-lg overflow-hidden\">\r\n");
      out.write("                        <div\r\n");
      out.write("                            class=\"h-48 bg-gradient-to-r from-purple-400 to-purple-600 flex items-center justify-center\">\r\n");
      out.write("                            <span class=\"text-6xl\">🛏️</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"p-6\">\r\n");
      out.write("                            <h3 class=\"text-xl font-semibold text-gray-800 mb-2\">Quarto Deluxe</h3>\r\n");
      out.write("                            <p class=\"text-gray-600 mb-4\">Quarto espaçoso com vista para o mar, frigobar e varanda\r\n");
      out.write("                                privativa.</p>\r\n");
      out.write("                            <div class=\"flex items-center justify-between mb-4\">\r\n");
      out.write("                                <span class=\"text-2xl font-bold text-purple-600\">R$ 250/noite</span>\r\n");
      out.write("                                <span class=\"text-sm text-gray-500\">👥 3 pessoas</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"flex items-center mb-4\">\r\n");
      out.write("                                <input type=\"checkbox\" id=\"room2\" class=\"room-checkbox mr-2\" data-room=\"Deluxe\"\r\n");
      out.write("                                    data-price=\"250\">\r\n");
      out.write("                                <label for=\"room2\" class=\"text-sm text-gray-700\">Selecionar este quarto</label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Suíte Premium -->\r\n");
      out.write("                    <div class=\"room-card bg-white rounded-lg shadow-lg overflow-hidden\">\r\n");
      out.write("                        <div class=\"h-48 bg-gradient-to-r from-yellow-400 to-yellow-600 flex items-center justify-center\">\r\n");
      out.write("                            <span class=\"text-6xl\">🏰</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"p-6\">\r\n");
      out.write("                            <h3 class=\"text-xl font-semibold text-gray-800 mb-2\">Suíte Premium</h3>\r\n");
      out.write("                            <p class=\"text-gray-600 mb-4\">Suíte luxuosa com jacuzzi, sala de estar e serviço de quarto\r\n");
      out.write("                                24h.</p>\r\n");
      out.write("                            <div class=\"flex items-center justify-between mb-4\">\r\n");
      out.write("                                <span class=\"text-2xl font-bold text-yellow-600\">R$ 450/noite</span>\r\n");
      out.write("                                <span class=\"text-sm text-gray-500\">👥 4 pessoas</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"flex items-center mb-4\">\r\n");
      out.write("                                <input type=\"checkbox\" id=\"room3\" class=\"room-checkbox mr-2\" data-room=\"Premium\"\r\n");
      out.write("                                    data-price=\"450\">\r\n");
      out.write("                                <label for=\"room3\" class=\"text-sm text-gray-700\">Selecionar este quarto</label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"text-center mt-8\">\r\n");
      out.write("                    <button id=\"continueBtn\"\r\n");
      out.write("                        class=\"bg-blue-600 hover:bg-blue-700 text-white font-semibold py-3 px-8 rounded-lg transition duration-300 disabled:bg-gray-400 disabled:cursor-not-allowed\"\r\n");
      out.write("                        disabled>\r\n");
      out.write("                        Continuar para Reserva →\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"js/script.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
